### ISSUE TITLE
vscf/src/bundler/index.ts:120     throw new Error("not found" + filePath);

### ISSUE THREAD

**Issue by mobailabs** [hamsterbase/vscf#1]
I ran the following command and got an error.

```
npm i
npm run eject
npm run restore
npm run build
```
vscf/src/bundler/index.ts:120
    throw new Error("not found" + filePath);
          ^
Error: not foundvscode/src/vs/base/common/buffer.ts
    at Bundler.<anonymous> (/Users/zhaopeng/project/github/vscf/src/bundler/index.ts:120:11)
    at Generator.throw (<anonymous>)
    at rejected (/Users/zhaopeng/project/github/vscf/src/bundler/index.ts:6:65)

**Comment by CaryTrivett** [comment]
base on vscode 1.78.2

**Comment by CaryTrivett** [comment]
1. open vscode 

2. git checkout b3e4e68a0bc
